version: 2
jobs:
  build:
    working_directory: ~/boot-clj-docker-docker
    docker:
      - image: docker:17.06-git  # should match Dockerfile's FROM
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: boot-clj-docker-docker-{{checksum "Dockerfile" }}
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker build -t ags799/boot-docker .
              docker tag ags799/boot-docker:latest ags799/boot-docker:$(git rev-parse --short HEAD)
              docker push ags799/boot-docker
            fi
